### PR TITLE
Update cachematrix.R

### PR DESCRIPTION
**Pull request by mendwell**

### CODE REVIEW

**Comment by pburkholder** [comment]
Hey - you need to merge this to master or evaluators may not see your work. I nearly gave you a zero on the entire assignment.  Like this:

```
git checkout master
get merge mendwell-patch-1
git push origin master
```

Your work will have the same SHA1 sum, but now graders will be able to find it.

P.

**Comment by mendwell** [comment]
Hi Peter,

Thanks for the headsup.  I'm really new to GitHub and R and wasn't sure if
I was doing this right.  Do I type that in the gitShell?

**Comment by mendwell** [comment]
Eep, I hope I did that right!

**Comment by pburkholder** [comment]
Looks good! Glad I could help  P.

On Sun, Feb 7, 2016 at 12:07 PM, mendwell notifications@github.com wrote:

> Eep, I hope I did that right!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mendwell/ProgrammingAssignment2/pull/1#issuecomment-181051657
> .

## 

_Peter Burkholder_ — Customer Success Engineer

Unavailability/OOO: Dec 26-Jan 11

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
http://www.linkedin.com/in/pburkholder  Twitter
http://www.twitter.com/pburkholder  Calendar
https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK

_CHEF_

CHEF.IO http://www.chef.io/

TM

_chef.io_ http://www.chef.io/   Blog http://www.chef.io/blog/   Facebook
https://www.facebook.com/getchefdotcom   Twitter
https://twitter.com/chef   Youtube https://www.youtube.com/getchef

**Pull request merged**
